### ISSUE TITLE
Nested variables support

### ISSUE THREAD

**Issue by vonpupp** [jezdez/envdir#46]
Hello,

I have a tmuxp profile as follows:

```
session_name: TEST
shell_command_before: envshell ./envars
windows:
- window_name: TEST
  layout: tiled
  panes:
    - shell_command:
      - docker exec -it $ODOOCONT /bin/bash
    - shell_command:
      - docker exec -it $ODOOCONT /bin/bash
```

As you can see for each pane I am loading with envshell the envars folder, which contains one variable as follows:

```
cat envars/ODOOCONT
test_container_19
```

I would like to do something like:
    ODOOCONT=$ODOOCONTAINER

Where $ODOOCONTAINER is defined on my local shell session before executing tmuxp. This doesn't work but is there any other way to achieve this?

Thank you!
